version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - .:/usr/src/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:12345678@db:5432/shopee-test"
  db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: shopee-test